#!/usr/bin/env python2.7

from more_parser import *
from operations import *
import nft
import sys


# compile regex to NFT M
regex = sys.argv[1]
length = len(regex)
counter = 0
parser = baseParser(regex, length, counter)
M = parser.parseRegexp()

# for each line in input:
for line in sys.stdin:

	line = line.rstrip('\n')

	# convert to singleton Mw
	Mw = nft.NFT.singleton(line)

	# compose Mw and M (input and regex)
	Mc = nft.NFT.compose(Mw, M)

	try:
		# print out if there is an accepting path
		transitions = nft.NFT.any_path(Mc)
		output = ''

		for t in transitions:
			if t.b is not '&':
				output = output + t.b

		print (output)
	except ValueError:
		pass