#!/usr/bin/env python3

from __future__ import print_function
import nfa
import sys
from mere_parser import *
import argparse

def run_nfa(M):
	argparser = argparse.ArgumentParser()
	argparser.add_argument('nfa')
	args = argparser.parse_args()
	m = M
	for line in sys.stdin:
		line = line.rstrip('\n')
		mw = nfa.NFA.intersect(m, nfa.NFA.singleton(line))
		if not mw.is_empty():
			print(line)

if __name__ == '__main__':
	regex = sys.argv[1]
	length = len(regex)
	counter = 0
	parser = baseParser(regex, length, counter)
	M = parser.parseRegexp()

	run_nfa(M)

